services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3927:3927"
    volumes:
      - ./app:/usr/src/todaytome/app
      - ./data:/usr/src/todaytome/data
      - /usr/src/todaytome/app/node_modules
    environment:
      - TZ=Asia/Seoul
      - PORT=3927
    env_file:
      - app/.env
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
